linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: emperror.dev/emperror

linters:
    enable-all: true
    disable:
        - funlen
        - gomnd
        - testpackage

        # TODO: fixme
        - godox
