name: Checks

on:
  push:
    branches:
      - master

jobs:
  build:
    name: FOSSA
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up GOPATH
        run: echo "::set-env name=GOPATH::$(go env GOPATH)"

      - name: Set Please overrides
        run: echo "::set-env name=PLZ_OVERRIDES::build.path:$PATH"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...
        env:
          GOFLAGS: -mod=readonly

      - name: Analyze
        run: ./pleasew run ///pleasings2//tools/misc:fossa -- analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
