name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
      PLZ_ARGS: -p

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: ./pleasew $PLZ_ARGS lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.11', '1.12', '1.13', '1.14', '1.15']
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
      PLZ_ARGS: -p

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: ./pleasew $PLZ_ARGS gotest

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: plz-out/log/coverage.txt
